# Use official OpenJDK 21 image
FROM eclipse-temurin:21-jdk

# Set working directory
WORKDIR /app

# Copy JAR file (adjust name accordingly)
COPY target/ApiGateway-0.0.1-SNAPSHOT.jar app.jar

# Expose port (make it unique per service)
EXPOSE 8081

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
