server:
  port: 9090

#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: AuthService
#          uri: lb://AuthService   # Eureka service name, not port
#          predicates:
#            - Path=/auth/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true




spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://tayyari-git-master-itsmefaishals-projects.vercel.app"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        # Auth service routes (no authentication required)
        - id: auth-service
          uri: https://tayyari-auth-service.onrender.com
          predicates:
            - Path=/auth/**
#          filters:
#            - StripPrefix=1

        # Admin service routes (requires ADMIN role)
        - id: question-service
          uri: https://tayyari-dbt8.onrender.com
          predicates:
            - Path=/question/**
          filters:
#            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                required-roles:
                - ROLE_ADMIN

        # Quiz service routes (requires User or Admin role)
        - id: quiz-service-admin
          uri: https://tayyari-3xqy.onrender.com
          predicates:
              - Path=/quiz/admin/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                required-roles:
                  - ROLE_ADMIN

        # User service routes (requires USER or ADMIN role)
        - id: quiz-service-public
          uri: https://tayyari-3xqy.onrender.com
          predicates:
            - Path=/quiz/public/**


        # User service routes (requires USER or ADMIN role)
        - id: user-service
          uri: https://tayyari-qchp.onrender.com
          predicates:
            - Path=/user/**
          filters:
#            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                required-roles:
                  - ROLE_ADMIN
                  - ROLE_USER

        # Order service routes (requires USER or ADMIN role)
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                required-role: USER

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: https://tayyari-93rl.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes